-- MySQL Script generated by MySQL Workbench
-- Tue Apr 19 09:47:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OnlineAppointmentDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OnlineAppointmentDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OnlineAppointmentDB` DEFAULT CHARACTER SET utf8 ;
USE `OnlineAppointmentDB` ;

-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Patient` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Patient` (
  `patient_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `dob` DATE NULL,
  `gender` VARCHAR(10) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(20) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`patient_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Clinic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Clinic` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Clinic` (
  `clinic_id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(20) NULL,
  PRIMARY KEY (`clinic_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Employee` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Employee` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `dob` DATE NULL,
  `gender` VARCHAR(10) NULL,
  `clinic` INT NULL,
  PRIMARY KEY (`employee_id`),
  INDEX `FK_Clinic_Employee_idx` (`clinic` ASC) VISIBLE,
  CONSTRAINT `FK_Clinic_Employee`
    FOREIGN KEY (`clinic`)
    REFERENCES `OnlineAppointmentDB`.`Clinic` (`clinic_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Doctor` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Doctor` (
  `doctor_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NULL,
  `name` VARCHAR(45) NULL,
  `dob` DATE NULL,
  `gender` VARCHAR(10) NULL,
  `clinic` INT NULL,
  PRIMARY KEY (`doctor_id`),
  INDEX `FK_Clinic_Doctor_idx` (`clinic` ASC) VISIBLE,
  INDEX `FK_Employee_Doctor_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `FK_Clinic_Doctor`
    FOREIGN KEY (`clinic`)
    REFERENCES `OnlineAppointmentDB`.`Clinic` (`clinic_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Employee_Doctor`
    FOREIGN KEY (`employee_id`)
    REFERENCES `OnlineAppointmentDB`.`Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Nurse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Nurse` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Nurse` (
  `nurse_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NULL,
  `name` VARCHAR(45) NULL,
  `dob` DATE NULL,
  `gender` VARCHAR(10) NULL,
  `clinic` INT NULL,
  PRIMARY KEY (`nurse_id`),
  INDEX `FK_Clinic_Nurse_idx` (`clinic` ASC) VISIBLE,
  INDEX `FK_Employee_Nurse_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `FK_Clinic_Nurse`
    FOREIGN KEY (`clinic`)
    REFERENCES `OnlineAppointmentDB`.`Clinic` (`clinic_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Employee_Nurse`
    FOREIGN KEY (`employee_id`)
    REFERENCES `OnlineAppointmentDB`.`Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Receptionist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Receptionist` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Receptionist` (
  `receptionist_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NULL,
  `name` VARCHAR(45) NULL,
  `dob` DATE NULL,
  `gender` VARCHAR(10) NULL,
  `clinic` INT NULL,
  PRIMARY KEY (`receptionist_id`),
  INDEX `FK_Employee_Receptionist_idx` (`employee_id` ASC) VISIBLE,
  INDEX `FK_Clinic_Receptionist_idx` (`clinic` ASC) VISIBLE,
  CONSTRAINT `FK_Employee_Receptionist`
    FOREIGN KEY (`employee_id`)
    REFERENCES `OnlineAppointmentDB`.`Employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Clinic_Receptionist`
    FOREIGN KEY (`clinic`)
    REFERENCES `OnlineAppointmentDB`.`Clinic` (`clinic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Services` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Services` (
  `service_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `price` VARCHAR(10) NULL,
  PRIMARY KEY (`service_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Fees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Fees` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Fees` (
  `fee_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NULL,
  `price` VARCHAR(20) NULL,
  PRIMARY KEY (`fee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Appointment` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Appointment` (
  `appointment_id` INT NOT NULL AUTO_INCREMENT,
  `patient` INT NULL,
  `doctor` INT NULL,
  `confirmation` VARCHAR(20) NULL,
  `type` VARCHAR(45) NULL,
  `location` INT NULL,
  `cancelled` TINYINT NULL,
  `date` DATETIME NULL,
  `service` INT NULL,
  `fee` INT NULL,
  PRIMARY KEY (`appointment_id`),
  INDEX `FK_Patient_Appointment_idx` (`patient` ASC) VISIBLE,
  INDEX `FK_Doctor_Appointment_idx` (`doctor` ASC) VISIBLE,
  INDEX `FK_Clinic_Appointment_idx` (`location` ASC) VISIBLE,
  INDEX `FK_Service_Appointment_idx` (`service` ASC) VISIBLE,
  INDEX `FK_Fee_Appointment_idx` (`fee` ASC) VISIBLE,
  CONSTRAINT `FK_Patient_Appointment`
    FOREIGN KEY (`patient`)
    REFERENCES `OnlineAppointmentDB`.`Patient` (`patient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Doctor_Appointment`
    FOREIGN KEY (`doctor`)
    REFERENCES `OnlineAppointmentDB`.`Doctor` (`doctor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Clinic_Appointment`
    FOREIGN KEY (`location`)
    REFERENCES `OnlineAppointmentDB`.`Clinic` (`clinic_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Service_Appointment`
    FOREIGN KEY (`service`)
    REFERENCES `OnlineAppointmentDB`.`Services` (`service_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Fee_Appointment`
    FOREIGN KEY (`fee`)
    REFERENCES `OnlineAppointmentDB`.`Fees` (`fee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Insurance_Providers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Insurance_Providers` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Insurance_Providers` (
  `provider_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`provider_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Insurance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Insurance` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Insurance` (
  `insurance_id` INT NOT NULL AUTO_INCREMENT,
  `patient` INT NULL,
  `provider` INT NULL,
  `member_id` VARCHAR(45) NULL,
  `group_no` VARCHAR(45) NULL,
  PRIMARY KEY (`insurance_id`),
  INDEX `FK_Patient_Insurance_idx` (`patient` ASC) VISIBLE,
  INDEX `FK_Provider_Insurance_idx` (`provider` ASC) VISIBLE,
  CONSTRAINT `FK_Patient_Insurance`
    FOREIGN KEY (`patient`)
    REFERENCES `OnlineAppointmentDB`.`Patient` (`patient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Provider_Insurance`
    FOREIGN KEY (`provider`)
    REFERENCES `OnlineAppointmentDB`.`Insurance_Providers` (`provider_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Card` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Card` (
  `card_id` INT NOT NULL AUTO_INCREMENT,
  `patient` INT NULL,
  `card_no` VARCHAR(45) NULL,
  `expiration` VARCHAR(20) NULL,
  `CVV` VARCHAR(10) NULL,
  PRIMARY KEY (`card_id`),
  INDEX `FK_Patient_Card_idx` (`patient` ASC) VISIBLE,
  CONSTRAINT `FK_Patient_Card`
    FOREIGN KEY (`patient`)
    REFERENCES `OnlineAppointmentDB`.`Patient` (`patient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Payment` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Payment` (
  `patient` INT NOT NULL,
  `card` INT NULL,
  `insurance_id` INT NULL,
  INDEX `FK_Insurance_Payment_idx` (`insurance_id` ASC) VISIBLE,
  INDEX `FK_Card_Payment_idx` (`card` ASC) VISIBLE,
  INDEX `FK_Patient_Payment_idx` (`patient` ASC) VISIBLE,
  CONSTRAINT `FK_Insurance_Payment`
    FOREIGN KEY (`insurance_id`)
    REFERENCES `OnlineAppointmentDB`.`Insurance` (`insurance_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Card_Payment`
    FOREIGN KEY (`card`)
    REFERENCES `OnlineAppointmentDB`.`Card` (`card_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Patient_Payment`
    FOREIGN KEY (`patient`)
    REFERENCES `OnlineAppointmentDB`.`Patient` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Schedule` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Schedule` (
  `schedule_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `doctor` INT NULL,
  `status` VARCHAR(45) NULL,
  `clinic` INT NULL,
  PRIMARY KEY (`schedule_id`),
  INDEX `FK_Doctor_Schedule_idx` (`doctor` ASC) VISIBLE,
  INDEX `FK_Clinic_Schedule_idx` (`clinic` ASC) VISIBLE,
  CONSTRAINT `FK_Doctor_Schedule`
    FOREIGN KEY (`doctor`)
    REFERENCES `OnlineAppointmentDB`.`Doctor` (`doctor_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Clinic_Schedule`
    FOREIGN KEY (`clinic`)
    REFERENCES `OnlineAppointmentDB`.`Clinic` (`clinic_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Specialties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Specialties` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Specialties` (
  `specialty_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`specialty_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Account` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Account` (
  `patient_id` INT NOT NULL,
  `password` VARCHAR(45) NULL,
  INDEX `FK_Patient_Account_idx` (`patient_id` ASC) VISIBLE,
  CONSTRAINT `FK_Patient_Account`
    FOREIGN KEY (`patient_id`)
    REFERENCES `OnlineAppointmentDB`.`Patient` (`patient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Prescriptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Prescriptions` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Prescriptions` (
  `prescription_id` INT NOT NULL AUTO_INCREMENT,
  `patient` INT NULL,
  `doctor` INT NULL,
  `date_prescribed` DATE NULL,
  `refills` INT NULL,
  PRIMARY KEY (`prescription_id`),
  INDEX `FK_Patient_Prescriptions_idx` (`patient` ASC) VISIBLE,
  INDEX `FK_Doctor_Prescriptions_idx` (`doctor` ASC) VISIBLE,
  CONSTRAINT `FK_Patient_Prescriptions`
    FOREIGN KEY (`patient`)
    REFERENCES `OnlineAppointmentDB`.`Patient` (`patient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Doctor_Prescriptions`
    FOREIGN KEY (`doctor`)
    REFERENCES `OnlineAppointmentDB`.`Doctor` (`doctor_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Medical_Records`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Medical_Records` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Medical_Records` (
  `patient` INT NOT NULL,
  `prescriptions` INT NULL,
  INDEX `FK_Patient_Records_idx` (`patient` ASC) VISIBLE,
  INDEX `FK_Prescriptions_Records_idx` (`prescriptions` ASC) VISIBLE,
  CONSTRAINT `FK_Patient_Records`
    FOREIGN KEY (`patient`)
    REFERENCES `OnlineAppointmentDB`.`Patient` (`patient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Prescriptions_Records`
    FOREIGN KEY (`prescriptions`)
    REFERENCES `OnlineAppointmentDB`.`Prescriptions` (`prescription_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Permissions` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Permissions` (
  `permission_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`permission_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Languages` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Languages` (
  `language_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  INDEX `FK_Doctor_Language_idx` (`language_id` ASC) VISIBLE,
  PRIMARY KEY (`language_id`),
  CONSTRAINT `FK_Doctor_Language`
    FOREIGN KEY (`language_id`)
    REFERENCES `OnlineAppointmentDB`.`Doctor` (`doctor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Reviews` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Reviews` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `patient` INT NULL,
  `doctor` INT NULL,
  `content` VARCHAR(200) NULL,
  PRIMARY KEY (`review_id`),
  INDEX `FK_Patient_Reviews_idx` (`patient` ASC) VISIBLE,
  INDEX `FK_Doctor_Reviews_idx` (`doctor` ASC) VISIBLE,
  CONSTRAINT `FK_Patient_Reviews`
    FOREIGN KEY (`patient`)
    REFERENCES `OnlineAppointmentDB`.`Patient` (`patient_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Doctor_Reviews`
    FOREIGN KEY (`doctor`)
    REFERENCES `OnlineAppointmentDB`.`Doctor` (`doctor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Notifications` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Notifications` (
  `notification_id` INT NOT NULL AUTO_INCREMENT,
  `appointment` INT NULL,
  `patient` INT NULL,
  `send_date` DATETIME NULL,
  `content` VARCHAR(100) NULL,
  PRIMARY KEY (`notification_id`),
  INDEX `FK_Patient_Notifications_idx` (`patient` ASC) VISIBLE,
  INDEX `FK_Appointment_Notifications_idx` (`appointment` ASC) VISIBLE,
  CONSTRAINT `FK_Appointment_Notifications`
    FOREIGN KEY (`appointment`)
    REFERENCES `OnlineAppointmentDB`.`Appointment` (`appointment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Patient_Notifications`
    FOREIGN KEY (`patient`)
    REFERENCES `OnlineAppointmentDB`.`Patient` (`patient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Doctor_Specialty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Doctor_Specialty` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Doctor_Specialty` (
  `doctor_specialty_id` INT NOT NULL AUTO_INCREMENT,
  `doctor` INT NULL,
  `specialty` INT NULL,
  PRIMARY KEY (`doctor_specialty_id`),
  INDEX `FK_specialty_ds_idx` (`specialty` ASC) VISIBLE,
  INDEX `FK_doctor_ds_idx` (`doctor` ASC) VISIBLE,
  CONSTRAINT `FK_specialty_ds`
    FOREIGN KEY (`specialty`)
    REFERENCES `OnlineAppointmentDB`.`Specialties` (`specialty_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_doctor_ds`
    FOREIGN KEY (`doctor`)
    REFERENCES `OnlineAppointmentDB`.`Doctor` (`doctor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`InsuranceP_Clinic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`InsuranceP_Clinic` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`InsuranceP_Clinic` (
  `InsuranceP_Clinic_id` INT NOT NULL AUTO_INCREMENT,
  `insurance` INT NULL,
  `clinic` INT NULL,
  PRIMARY KEY (`InsuranceP_Clinic_id`),
  INDEX `FK_Clinic_IC_idx` (`clinic` ASC) VISIBLE,
  INDEX `FK_Insurance_IC_idx` (`insurance` ASC) VISIBLE,
  CONSTRAINT `FK_Insurance_IC`
    FOREIGN KEY (`insurance`)
    REFERENCES `OnlineAppointmentDB`.`Insurance_Providers` (`provider_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Clinic_IC`
    FOREIGN KEY (`clinic`)
    REFERENCES `OnlineAppointmentDB`.`Clinic` (`clinic_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Appointment_Fee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Appointment_Fee` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Appointment_Fee` (
  `Appointment_Fee_id` INT NOT NULL AUTO_INCREMENT,
  `Appointment` INT NULL,
  `Fee` INT NULL,
  PRIMARY KEY (`Appointment_Fee_id`),
  INDEX `FK_Fee_AF_idx` (`Appointment` ASC) VISIBLE,
  INDEX `FK_Appointment_AF_idx` (`Fee` ASC) VISIBLE,
  CONSTRAINT `FK_Fee_AF`
    FOREIGN KEY (`Appointment`)
    REFERENCES `OnlineAppointmentDB`.`Appointment` (`appointment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Appointment_AF`
    FOREIGN KEY (`Fee`)
    REFERENCES `OnlineAppointmentDB`.`Fees` (`fee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Doctor_Language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Doctor_Language` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Doctor_Language` (
  `Doctor_Language_id` INT NOT NULL AUTO_INCREMENT,
  `doctor` INT NULL,
  `language` INT NULL,
  PRIMARY KEY (`Doctor_Language_id`),
  INDEX `FK_doctor_DL_idx` (`doctor` ASC) VISIBLE,
  INDEX `FK_language_DL_idx` (`language` ASC) VISIBLE,
  CONSTRAINT `FK_doctor_DL`
    FOREIGN KEY (`doctor`)
    REFERENCES `OnlineAppointmentDB`.`Doctor` (`doctor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_language_DL`
    FOREIGN KEY (`language`)
    REFERENCES `OnlineAppointmentDB`.`Languages` (`language_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Employee_Permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Employee_Permissions` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Employee_Permissions` (
  `Employee_Permissions_id` INT NOT NULL AUTO_INCREMENT,
  `employee` INT NULL,
  `permission` INT NULL,
  PRIMARY KEY (`Employee_Permissions_id`),
  INDEX `FK_employee_EP_idx` (`employee` ASC) VISIBLE,
  CONSTRAINT `FK_employee_EP`
    FOREIGN KEY (`employee`)
    REFERENCES `OnlineAppointmentDB`.`Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_permission_EP`
    FOREIGN KEY (`permission`)
    REFERENCES `OnlineAppointmentDB`.`Permissions` (`permission_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Doctor_Services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Doctor_Services` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Doctor_Services` (
  `Doctor_Services_id` INT NOT NULL AUTO_INCREMENT,
  `doctor` INT NULL,
  `service` INT NULL,
  PRIMARY KEY (`Doctor_Services_id`),
  INDEX `FK_service_DS_idx` (`service` ASC) VISIBLE,
  INDEX `FK_doctor_DS_idx` (`doctor` ASC) VISIBLE,
  CONSTRAINT `FK_doctor_DSER`
    FOREIGN KEY (`doctor`)
    REFERENCES `OnlineAppointmentDB`.`Doctor` (`doctor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_service_DSER`
    FOREIGN KEY (`service`)
    REFERENCES `OnlineAppointmentDB`.`Services` (`service_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineAppointmentDB`.`Nurse_Services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineAppointmentDB`.`Nurse_Services` ;

CREATE TABLE IF NOT EXISTS `OnlineAppointmentDB`.`Nurse_Services` (
  `Nurse_Services_id` INT NOT NULL AUTO_INCREMENT,
  `nurse` INT NULL,
  `service` INT NULL,
  PRIMARY KEY (`Nurse_Services_id`),
  INDEX `FK_nurse_NS_idx` (`nurse` ASC) VISIBLE,
  INDEX `FK_service_NS_idx` (`service` ASC) VISIBLE,
  CONSTRAINT `FK_nurse_NS`
    FOREIGN KEY (`nurse`)
    REFERENCES `OnlineAppointmentDB`.`Nurse` (`nurse_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_service_NS`
    FOREIGN KEY (`service`)
    REFERENCES `OnlineAppointmentDB`.`Services` (`service_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
